version: '3.4'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: johto
      POSTGRES_PASSWORD: boofar
    ports:
      - "5433:5432"
    volumes:
      - ./sql/init.sql.d:/docker-entrypoint-initdb.d
      - /tmp/johto-db/data:/var/lib/postgresql/data
  api:
    build: ./
    environment:
      POSTGRES_USER: johto
      POSTGRES_PASSWORD: boofar
    restart: always
    depends_on:
      - db
    links:
      - db
    ports:
      - "8080:8080"
